title = 'Coronium GS Server'
project = 'Coronium GS Server'
description = 'Coronium GS Docs'
full_description = 'A real-time multi-player game server built on Luvit.io'
format = 'markdown'
file = '.'
boilerplate = true
examples = { 'examples' }
topics = { 'license.md', 'readme.md', 'development.md' }
sort = true
template = "tpl"
style = "tpl"
not_luadoc = true
tparam_alias('player','Client')
tparam_alias('client', 'Client')
tparam_alias('tab', 'table')
